### ISSUE TITLE
Out of the box it can't find the shared-lib

### ISSUE THREAD

**Issue by Chrisbright10** [sourcygen/electron-angular-quick-start#4]
Error: src/app/components/mutiples/mutiples.component.ts:4:32 - error TS2307: Cannot find module 'shared-lib' or its corresponding type declarations.

import { WindowApiConst } from 'shared-lib';

**Comment by aadiene** [comment]
Hi @Chrisbright10, did you launch the project with `npm start` ?

**Comment by aadiene** [comment]
I guess the `shared-lib` build was not completely finished when the `angular-app` started. To prevent that, generated files are now part of sources `v2.0.2` until I find a better solution. Feel free to close the issue after testing.
Thanks anyway for the feedback 👍 ! 

If you find this project useful, do not forget to add one ⭐ which will be very appreciated !

**Comment by Chrisbright10** [comment]
So that helped fix part of the issue... the other part is this...

![image](https://user-images.githubusercontent.com/2694666/126693093-4bc01d3d-91e5-41a3-b6d9-5293b886cd92.png)

I could change the import to be a "../../" relative path... but i am not sure if that would mess up anything you have going on.

when i do change it to a relative path in those two files it compiles.. but then i get this screen and no app pops up (i was assuming it would pop up a live electron app in dev mode)

![image](https://user-images.githubusercontent.com/2694666/126694060-82c6680b-077c-4a3c-ad71-833cefddf76c.png)

**Comment by Chrisbright10** [comment]
Also the package function was not working until I added similar relative paths to electron-app's multiples.service.ts and index.ts. So now i can get a build out of it but it still will not run dev mode with hot reload (which is what i am expecting from dev mode). If i can get that running I am wanting to switch my app over to this style because frankly i like it better than the shell i began with.

**Comment by aadiene** [comment]
Actually you do not need any change to make it work. Can you give me your `node` and `npm` version ? 
Do not use your existing modified repo and make a new `git clone` from scratch :
- Run `npm install && npm start`

Sometimes on VSCode you may have compilation false positives that do not affect the build process. Just restart VSCode to make those disappear.

**Comment by aadiene** [comment]
After testing on my Windows machine, it seems that the problem comes from `npm-watch` which I use to reload the electron `main process`. It works perfectly fine on MacOS though.

Just to make sure, I want you to test this. From clean repo, in the `package.json` file, replace the following line :
> "start:electron-app": "wait-on http://localhost:4200 && npm-watch restart-electron-app",

by this one :
> "start:electron-app": "wait-on http://localhost:4200 && npm run restart-electron-app",

You will have live-reload regarding any impact on the `angular app`, but you will have to restart everything to see changes from the `main process`.

**Comment by Chrisbright10** [comment]
That worked perfectly, the paths still needed to be altered to make it work on windows, not sure why, but everything is good with that npm-watch to npm run change above!

**Comment by aadiene** [comment]
Thanks for your feedback @Chrisbright10. I replaced `npm-watch` by a script using `chokidar` that restarts `electron-forge` on any change in the `main process` sources. Electron E2E tests were not passing on Windows either. It is now fixed !

Regarding the `shared-lib` path, I suspect that you do not have the latest version of `npm`. Please follow once more the [Getting started](https://github.com/sourcygen/electron-angular-quick-start#getting-started) instructions and see if you still need **relative** paths.

And again, if you find this project useful, do not forget to share and add one ⭐ !
