### ISSUE TITLE
how we can use multiple ipc services using this structure ?

### ISSUE THREAD

**Issue by MMJ184** [sourcygen/electron-angular-quick-start#44]
using this structure how do we manage multiple IPC services? because I am using SQLite as db, I need multiple ipc services for module vise crud operation.

**Comment by aadiene** [comment]
Hi @MMJ184, what do you mean by "IPC services" ?
Happy to help, but before going any futher I would like to be sure about your question.
Could you please elaborate your needs with more details and examples.

**Comment by MMJ184** [comment]
Hi, @aadiene,
I need to create an Inventory app in (Electron + angular) with (Sqlite + Typeorm) with a repository pattern.

So, I require many ipcMain channels to perform database operations and get data right.

In this structure, you are connecting for data send and receive electron To angular using ipcMain (On WindowApiConst). 
but you create only one method for that if anyone requires multiple then how can we manage? can you give any example?

**Comment by aadiene** [comment]
Hi @MMJ184 , do you still need an example of how to implement multiple services ?

**Comment by MMJ184** [comment]
> Hi @MMJ184 , do you still need an example of how to implement multiple services ?

Yes, if possible please guide me

**Comment by MrTob** [comment]
any news about this?

**Comment by MMJ184** [comment]
> any news about this?

No, not yet
