### ISSUE TITLE
[Question] Warnings about unused files during Angular app compilation 

### ISSUE THREAD

**Issue by minerjed** [sourcygen/electron-angular-quick-start#49]
Big thanks for this quick start guide.  Look everywhere on the web and this guide was the only one that was current.  It has helped me immensely.  I just upgraded to the latest version and I have two questions.  What is causing these warnings. - 

Warning: C:/Users/4dunc/Desktop/mining/desktop-wallet/xcashdtwallet/workspaces/shared-lib/apis/window-api-consts.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

and 

I am getting this error in my updated code.

[15248:0505/120624.763:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)

Any idea what it might be.  I narrowed it down to the upgrade of angular but that is all I have figured out.

One other question sandbox is set to true in production.  Is this correct?
	"production": {
		"configId": "production",
		"mainLogFile": "main.log",
		"mainLogLevel": "error",
		"isIconAvailable": false,
		"isSandbox": true,
		"isOpenDevTools": false  

Thanks again...

**Comment by aadiene** [comment]
Hi @minerjed, thanks for the feed back.
Could you provide more details about how to reproduce. What did you do exactly ?
Dont forget to mention your node and npm versions.

**Comment by aadiene** [comment]
About `sandbox` default is true. So yeah should be true in production unless you want to use dynamic dependancies from preload script. By the way, its is disabled when developing  because the scripts are not bundled by webpack yet.

**Comment by minerjed** [comment]
Running on Windows 10, node v18.14.2, and npm 9.5.0.  No changes just downloaded the code and built.  When I issue the command 'npm run start' I get these warnings.   
![warn](https://github.com/sourcygen/electron-angular-quick-start/assets/42452856/51dd6be8-f9a1-4b8d-937b-6be4f89aae2e)

The other warning I am getting "[15248:0505/120624.763:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)" does not show up so it is not an issue with your code.

Thanks

**Comment by aadiene** [comment]
Lately, I did not have time to fix this, but I am about to. 
Stay tuned.

**Comment by minerjed** [comment]
Funny, I just looked at this again last week.  I tried the update again and not seeing the "Add only entry points" message now.  As for this error "[15248:0505/120624.763:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js " it is related to electron v24.  I am currently running ^23.3.13" but when I upgrade to any version v24 or higher get the error message.

These are the notable changes in electron v24
 Stack Changes
Chromium 112.0.5615.49
[New in Chrome 112] (https://developer.chrome.com/blog/new-in-chrome-112/)
[New in Chrome 111] (https://developer.chrome.com/blog/new-in-chrome-111/)
[New in DevTools 112] (https://developer.chrome.com/blog/new-in-devtools-112/)
[New in DevTools 111] (https://developer.chrome.com/blog/new-in-devtools-111/)
Node.js 18.14.0

V8 11.2

The new error I ran into is when I build the install scripts and run the install, I get a blank screen when I run the application.  When I remove the sandbox line and build the install scripts it works fine.  Did not look at this very long so it may be something I have set up incorrectly.   

Thanks...

**Comment by aadiene** [comment]
Thanks for your inputs @minerjed. It was a journey though with everything to fix and upgrade.
Feel free to check and let me know if I have missed something.

**Comment by minerjed** [comment]
Do you know what was causing the error "[15248:0505/120624.763:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js" ?

**Comment by aadiene** [comment]
Did not catch that one while upgrading sorry. Do you still have it ?
Checkout last version and compare with your project.

**Comment by minerjed** [comment]
Looks like it was some sort of chrome.scripting issue.  Support was added in electron V26.x.  I upgraded electron to V26.6.0 and error is gone. https://github.com/electron/electron/pull/39676

Thanks for all the help....

**Comment by minerjed** [comment]
I attempted to upgrade to your latest version but ran into a bunch of webpack issue.  Did not take the time to figure out.  I did upgrade angular and like I said I am on electron V26.  That is good enough for now.  Thanks again.
