### ISSUE TITLE
Question regarding cypress in the Electron app

### ISSUE THREAD

**Issue by gpinkham** [sourcygen/electron-angular-quick-start#54]
I am curious if you have run Cypress from inside the electron app (in the electron-app workspace)?   I'm having the hardest time getting that working.    but basically using npm run start I can launch a cypress test from the app.    if I package it up and install it on a mac the app fails to start with 
`Uncaught Exception:
Error: Cannot find module './lib/cypress'`

which is coming from cypress/index.mjs 
been trying to see if unpacking the asar will help but can't seem to get anything unpacked.

**Comment by gpinkham** [comment]
I guess I could ping every 29 days to keep it from getting stale.

**Comment by aadiene** [comment]
Hi @gpinkham (sorry for the late response), do you still need assistance with this ?
If not could please share your findings ?

**Comment by gpinkham** [comment]
No worries.    so I honestly haven't anything with the Cypress part in a bit.      my goal was to generate test data using the the electron app I wrote (which submits it to a backend system via API) and then I wanted to use Cypress to run automated UI tests against the backend from within the electron app.     Basically use the results of the API calls to feed into the Cypress tests.    But yeah I could never get the App to load if I include the Cypress tests in the production build.    Only works when running in dev mode (npm run start).      If its not something you have done we can probably close this.    I'd hate for you to put any time into it as I don't honestly know if I want to run the tests any more.    Been using it without that feature for months now.
