### ISSUE TITLE
 [BUG] cannot find module : Preload.js

### ISSUE THREAD

**Issue by AniketDha** [sourcygen/electron-angular-quick-start#55]
I tried to build the project. After project is up and running. It gives the error:
`Unable` to load preload script: D:\task\XE5\.webpack\renderer\main_window\preload.js``
Error: Cannot find module 'D:\task\XE5\.webpack\renderer\main_window\preload.js'

**Comment by peter890** [comment]
I also have this problem. Occurs only during development build

**Comment by aadiene** [comment]
Hi @AniketDha @peter890 
That's very strange ! Could you please share reproduction details and your system info (os, node, npm) ?

**Comment by AniketDha** [comment]
Hi,
os: Windows 11/ MAC OS, node: 18.16.1, npm: 6.14
This issue gets resolved only of I use your package-lock.json.

Thanks
Aniket Dhamal
